export * from './Cosa/Cosa'
export * from './NubeP5/NubeP5'
export * from './FocoP5/FocoP5'
export * from './NopalP5/NopalP5'
export * from './ConejoP5/ConejoP5'
export * from './PecesP5/PecesP5'
export * from './AbejaP5/AbejaP5'